import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from ' /styles/Home.module.css'
import React from 'react'
import { Maintitle } from '../components/Maintitle'
import { Opentext } from '../components/Opentext'
import { Footer } from '../components/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>タソカレトキ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <Maintitle />
        </div>
        <div className={styles.center}>
          <Opentext />
        </div>

        
        <Footer />
      </main>
      
    </>
  )
}
